- docker: "alloy"
  github: "alloy"
  deploy:
    release: "v1.12.0-a556c51"

- docker: "kayron"
  github: "kayron"
  deploy:
    release: "v0.5.3"

- docker: "specta"
  github: "specta"
  deploy:
    release: "v0.3.0"

- docker: "splits-lite"
  github: "splits-lite"
  deploy:
    release: "v0.2.0"
    preview: true
