- docker: "alloy"
  github: "alloy"
  deploy:
    release: "v1.12.1-fd79cf7"

- docker: "kayron"
  github: "kayron"
  deploy:
    release: "v0.5.3"

- docker: "specta"
  github: "specta"
  deploy:
    release: "v0.3.1"

- docker: "splits-lite"
  github: "splits-lite"
  deploy:
    release: "v0.2.1"
    preview: true
